### ISSUE TITLE
Desnecessário chave de segurança

### ISSUE THREAD

**Issue by brlink-org** [brlink-org/mkauth-recibo-whatsapp#2]

**Comment by cirinho** [comment]
@MauricioSarmento conforme conversamos, já não é mais necessário a chave de segurança tendo em vista que agora é um addon dentro do mk-auth e é necessário estar logado no /admin tanto que ao tentar colocar o link diretamente retorna acesso negado e já redireciona para o login do /admin.
![image](https://github.com/brlink-org/mkauth-recibo-whatsapp/assets/3154405/db856ad6-6273-49b9-83d8-dd1eeb23c7f2)
Então basta colocar o número do título ... talvez no lugar da chave de segurança possa exibir as informações da mensagem para ver se está correto e solicitar uma confirmação antes de enviar ?
